# Generated by Django 5.2 on 2026-04-02 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('math', 'Mathematics'), ('science', 'Science'), ('history', 'History'), ('literature', 'Literature'), ('technology', 'Technology'), ('language', 'Language'), ('other', 'Other')], default='other', max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('max_score', models.FloatField(default=0)),
                ('total_marks', models.FloatField(default=0)),
                ('marks_per_question', models.FloatField(default=1)),
                ('time_limit_per_question', models.FloatField(default=1, help_text='Minutes per question')),
                ('total_time_limit', models.FloatField(default=0, help_text='Total time in minutes')),
                ('pass_criteria', models.FloatField(default=50, help_text='Percentage required to pass')),
                ('instructions', models.TextField(blank=True, default='')),
                ('conclusion', models.TextField(blank=True, default='')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('allow_jump_around', models.BooleanField(default=False)),
                ('only_move_forward', models.BooleanField(default=False)),
                ('randomize_order', models.BooleanField(default=False)),
                ('allow_blank_answers', models.BooleanField(default=False)),
                ('penalize_incorrect_answers', models.BooleanField(default=False)),
                ('disable_right_click', models.BooleanField(default=False)),
                ('disable_copy_paste', models.BooleanField(default=False)),
                ('disable_translate', models.BooleanField(default=False)),
                ('disable_autocomplete', models.BooleanField(default=False)),
                ('disable_spellcheck', models.BooleanField(default=False)),
                ('disable_printing', models.BooleanField(default=False)),
                ('allow_retakes', models.BooleanField(default=False)),
                ('number_of_retakes', models.IntegerField(default=1)),
                ('is_public', models.BooleanField(default=False)),
                ('receive_email_notifications', models.BooleanField(default=False)),
                ('notification_emails', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('rank', models.IntegerField(default=1)),
                ('secure_uuid', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('multiplechoice', 'Multiple Choice'), ('multipleresponse', 'Multiple Response'), ('truefalse', 'True / False'), ('fillintheblank', 'Fill in the Blank')], max_length=30)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.test')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AllowedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_emails', to='app.test')),
            ],
            options={
                'unique_together': {('test', 'email')},
            },
        ),
    ]
