# Generated by Django 5.2 on 2026-04-03 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='MalpracticeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('no_face', 'No Face Detected'), ('multiple_faces', 'Multiple Faces Detected'), ('eye_movement', 'Eye Movement Detected'), ('head_turned_left', 'Head Turned Left'), ('head_turned_right', 'Head Turned Right'), ('talking_detected', 'Talking Detected'), ('object_detected', 'Object Detected')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='malpractice_logs', to='app.candidate')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malpractice_logs', to='app.test')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('score', models.FloatField(blank=True, null=True)),
                ('total_marks', models.FloatField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('time_taken', models.IntegerField(blank=True, help_text='Seconds taken to complete', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('alert_count', models.IntegerField(default=0)),
                ('force_exited', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='app.candidate')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='app.test')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
