# Generated by Django 5.2 on 2026-04-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_malpracticelog_testsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedemail',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allowedemail',
            name='passcode',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
