# Generated by Django 5.2 on 2026-04-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_allowedemail_is_used_allowedemail_passcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='malpracticelog',
            name='student_id',
        ),
        migrations.AddField(
            model_name='testassignment',
            name='selection_sent',
            field=models.BooleanField(default=False),
        ),
    ]
