# Generated by Django 5.2 on 2025-04-28 23:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_test_notification_emails_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_Duplicated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='test_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        #migrations.CreateModel(
            #name='StudentCapture',
            #fields=[
                #('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
               # ('image', models.ImageField(upload_to='captures/')),
               # ('timestamp', models.DateTimeField(auto_now_add=True)),
               # ('is_valid', models.BooleanField(default=False)),
               # ('validation_message', models.CharField(blank=True, max_length=255)),
               # ('face_detected', models.BooleanField(default=False)),
               # ('multiple_faces', models.BooleanField(default=False)),
               # ('looking_straight', models.BooleanField(default=False)),
               # ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            #],
            #options={
              #  'ordering': ['-timestamp'],
           # },
      #  ),
    ]
